### ISSUE TITLE
网页上的一些bug

### ISSUE THREAD

**Issue by hui-shao** [Misaka-IoT/misaka-vue#24]
- [x] bug 指正
- [ ] 新功能/ui 设计提议
- [ ] 某系列作品介绍内容修正
      ———在下方详细描述问题———

---

两个问题：

1. [人际关系](https://www.misaka-mikoto.jp/InterpersonalRelationship) 页面，部分说明文字和页脚文字重叠在一起。
  如图：
![bef](https://user-images.githubusercontent.com/31568606/215990158-3448b2f9-12e9-4be4-bf98-61523eac41ba.png)
  本来想开个 PR 修一下，但似乎没在源码里找到。搜索仓库可见，页面源码里引用了这个样式，但我在仓库里没找到相应 style 的定义。
）是不是截至我发 issue 这个时间，网页并不是用仓库里这份代码构建的，源码和网页对不上....
![2023-02-01_163200](https://user-images.githubusercontent.com/31568606/215991465-c1f49e98-4d68-4e5f-b65d-564e587fdd82.png)
  修复方式就是把 `height: 75vh;` 去掉。（网页内容不能硬编码高度），修复效果如下：
![aft](https://user-images.githubusercontent.com/31568606/215992869-ac02b2f0-ba82-4e21-bca9-781e3986d285.png)

2. [新测试页面](https://www.misaka-mikoto.jp/relationship) 上条当妈的图片是 404 状态。
  
![2023-02-01_164350](https://user-images.githubusercontent.com/31568606/215993822-19bdc0ee-bea8-401a-a72b-43363e47883f.png)

**Comment by misaka-fans** [comment]
看看上条当麻图片的src，你会知道一切（）
主要是还没有画好awa

**Comment by hui-shao** [comment]
> 看看上条当麻图片的src，你会知道一切（）
> 主要是还没有画好awa

啊哈，那我就“静候佳音”啦

**Comment by misaka-fans** [comment]
mit声明已单独移步至关于页面，图片缺失问题因为缺少画师的原因无法修复，已通过删掉图片的暴力方式解决![image](https://user-images.githubusercontent.com/104608787/235171032-48605d2d-0c44-4a65-a512-016c333275a5.jpeg)
