### ISSUE TITLE
动画资源失效

### ISSUE THREAD

**Issue by abigdealman** [Misaka-IoT/misaka-vue#50]
经查阅，链接中第一季和第二季动画资源已失效。如果可以的话，我可以提供同样的RAW资源文件。

**Comment by misaka-fans** [comment]
资源确实没了，希望能提供新的链接！最好是存在Onedrive/mega/google drive上的文件

**Comment by abigdealman** [comment]
> 资源确实没了，希望能提供新的链接！最好是存在Onedrive/mega/google drive上的文件

我可以上传到Onedrive中，但是分享链接似乎要挂梯子才能查看😂门槛会不会太高了？
如果这不是问题，我可以把链接发给你。

**Comment by misaka-fans** [comment]
> 我可以上传到Onedrive中，但是分享链接似乎要挂梯子才能查看😂门槛会不会太高了？
> 
> 如果这不是问题，我上传后可以把链接发给你。我的资源都是储存在本地硬盘中，如果你需要我才会上传到Onedrive，这需要一段时间。

可以试试Microsoft365里的Sharepoint，这个上面的文件网页版可以直接下载的。但是onedrive其实也是可以接受的吧，用客户端还是可以正常上传下载的，速度慢点罢了。只要在资源页提示前往App打开链接就行。毕竟国外网盘存资源算稳定点。😘

**Comment by abigdealman** [comment]
> > 我可以上传到Onedrive中，但是分享链接似乎要挂梯子才能查看😂门槛会不会太高了？
> > 如果这不是问题，我上传后可以把链接发给你。我的资源都是储存在本地硬盘中，如果你需要我才会上传到Onedrive，这需要一段时间。
> 
> 可以试试Microsoft365里的Sharepoint，这个上面的文件网页版可以直接下载的。但是onedrive其实也是可以接受的吧，用客户端还是可以正常上传下载的，速度慢点罢了。只要在资源页提示前往App打开链接就行。毕竟国外网盘存资源算稳定点。😘

https://1drv.ms/f/c/46d0f49f6fdf53a3/Ehs1p3_5fChFtRHRYBKMTVwBcng_FqebDVLqjkCvq009vQ?e=O3cfMA
这是第一季的链接，我测试后应该要翻墙进去的，第二季还在上传。

**Comment by misaka-fans** [comment]
> > > 我可以上传到Onedrive中，但是分享链接似乎要挂梯子才能查看😂门槛会不会太高了？
> 
> > > 如果这不是问题，我上传后可以把链接发给你。我的资源都是储存在本地硬盘中，如果你需要我才会上传到Onedrive，这需要一段时间。
> 
> > 
> 
> > 可以试试Microsoft365里的Sharepoint，这个上面的文件网页版可以直接下载的。但是onedrive其实也是可以接受的吧，用客户端还是可以正常上传下载的，速度慢点罢了。只要在资源页提示前往App打开链接就行。毕竟国外网盘存资源算稳定点。😘
> 
> 
> 
> https://1drv.ms/f/c/46d0f49f6fdf53a3/Ehs1p3_5fChFtRHRYBKMTVwBcng_FqebDVLqjkCvq009vQ?e=O3cfMA
> 
> 这是第一季的链接，我测试后应该要翻墙进去的，第二季还在上传。

好的，麻烦你啦！
实在是没办法，只能让大家自己想办法解决梯子的问题了( ；´Д｀)

**Comment by abigdealman** [comment]
整理了一下，
[**_第一季资源_**](https://1drv.ms/f/c/46d0f49f6fdf53a3/Ehs1p3_5fChFtRHRYBKMTVwBcng_FqebDVLqjkCvq009vQ?e=O3cfMA)
[**_第二季资源_**](https://1drv.ms/f/c/46d0f49f6fdf53a3/EilI5RDosDRLnNTNbGDIAmABxbufe4gxypdR7P2FS9xC_w?e=TMu1zi)
  这两季资源分别来自VCB-Studio和ReinForce压制组。其中RF组中的扫图(Scans)和CD用VCB的同类型资源替换了（因为RF组体积惊人😂）  。因为两个组都没有做字幕，我便找来了对应的外挂字幕文件改名之后放到文件夹里面去了。所以说这两个资源收藏价值是大于实用价值的。
  另外，我将VCB组整理的Wallpapers单独列出一个[**_链接_**](https://1drv.ms/f/c/46d0f49f6fdf53a3/Ejhnk4QeuJZHm6UrwzVcfLQB8Te5usjhLvX6zdbZDCsA9w?e=usacuq)，这个里面的pictures来源是P站和官方画册，有美琴和超炮四人组的不少图片（话说VCB组的建立者、前任队长LittlePox也算是一个重度炮粉🤭），你可以从中挑选一些放到照片墙上或者作为资源链接公开。
  最后，祝愿作者在新的一年里心想事成，万事如意！也希望御坂小站能够长久且顺利地开展下去！(★ ω ★)

**Comment by abigdealman** [comment]
> > > > 我可以上传到Onedrive中，但是分享链接似乎要挂梯子才能查看😂门槛会不会太高了？
> > 
> > 
> > > > 如果这不是问题，我上传后可以把链接发给你。我的资源都是储存在本地硬盘中，如果你需要我才会上传到Onedrive，这需要一段时间。
> > 
> > 
> > > 
> > 
> > 
> > > 可以试试Microsoft365里的Sharepoint，这个上面的文件网页版可以直接下载的。但是onedrive其实也是可以接受的吧，用客户端还是可以正常上传下载的，速度慢点罢了。只要在资源页提示前往App打开链接就行。毕竟国外网盘存资源算稳定点。😘
> > 
> > 
> > https://1drv.ms/f/c/46d0f49f6fdf53a3/Ehs1p3_5fChFtRHRYBKMTVwBcng_FqebDVLqjkCvq009vQ?e=O3cfMA
> > 这是第一季的链接，我测试后应该要翻墙进去的，第二季还在上传。
> 
> 好的，麻烦你啦！ 实在是没办法，只能让大家自己想办法解决梯子的问题了( ；´Д｀)

  整理了一下，
[**_第一季资源_**](https://1drv.ms/f/c/46d0f49f6fdf53a3/Ehs1p3_5fChFtRHRYBKMTVwBcng_FqebDVLqjkCvq009vQ?e=O3cfMA)
[**_第二季资源_**](https://1drv.ms/f/c/46d0f49f6fdf53a3/EilI5RDosDRLnNTNbGDIAmABxbufe4gxypdR7P2FS9xC_w?e=TMu1zi)
  这两季资源分别来自VCB-Studio和ReinForce压制组。其中RF组中的扫图(Scans)和CD用VCB的同类型资源替换了（因为RF组体积惊人😂）  。因为两个组都没有做字幕，我便找来了对应的外挂字幕文件改名之后放到文件夹里面去了。所以说这两个资源收藏价值是大于实用价值的。
  另外，我将VCB组整理的Wallpapers单独列出一个[**_链接_**](https://1drv.ms/f/c/46d0f49f6fdf53a3/Ejhnk4QeuJZHm6UrwzVcfLQB8Te5usjhLvX6zdbZDCsA9w?e=usacuq)，这个里面的pictures来源是P站和官方画册，有美琴和超炮四人组的不少图片（话说VCB组的建立者、前任队长LittlePox也算是一个重度炮粉🤭），你可以从中挑选一些放到照片墙上或者作为资源链接公开。
  最后，祝愿作者在新的一年里心想事成，万事如意！也希望御坂小站能够长久且顺利地开展下去！(★ ω ★)
